/**
 * onboarding.ts — MemPalace first-run setup.
 *
 * Direct port of mempalace/onboarding.py (programmatic interface).
 *
 * Seeds the entity registry with confirmed data so MemPalace knows the
 * user's world from minute one — before a single session is indexed.
 *
 * Note: The Python original uses interactive prompts. This Node.js port
 * exposes the same functionality as a programmatic API. To run an
 * interactive flow, wrap these functions with readline or similar.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { EntityRegistry, COMMON_ENGLISH_WORDS } from './entity-registry';
import { detectEntities, scanForDetection } from './entity-detector';

// ── Default wing taxonomies by mode ─────────────────────────────────────────

export const DEFAULT_WINGS: Record<string, string[]> = {
  work: ['projects', 'clients', 'team', 'decisions', 'research'],
  personal: ['family', 'health', 'creative', 'reflections', 'relationships'],
  combo: ['family', 'work', 'health', 'creative', 'projects', 'reflections'],
};

export type OnboardingMode = 'work' | 'personal' | 'combo';

export interface OnboardingPerson {
  name: string;
  relationship?: string;
  context?: 'personal' | 'work';
}

export interface OnboardingConfig {
  mode: OnboardingMode;
  people: OnboardingPerson[];
  projects?: string[];
  aliases?: Record<string, string>;
  wings?: string[];
  configDir?: string;
}

// ── Auto-detect from files ──────────────────────────────────────────────────

/**
 * Scan a directory for additional entity candidates.
 */
export function autoDetect(directory: string, knownPeople: OnboardingPerson[]): Array<{ name: string; confidence: number; signals: string[] }> {
  const knownNames = new Set(knownPeople.map(p => p.name.toLowerCase()));

  try {
    const files = scanForDetection(directory);
    if (files.length === 0) return [];
    const detected = detectEntities(files);
    return detected.people.filter(e =>
      !knownNames.has(e.name.toLowerCase()) && e.confidence >= 0.7,
    );
  } catch {
    return [];
  }
}

/**
 * Flag names that are also common English words.
 */
export function warnAmbiguous(people: OnboardingPerson[]): string[] {
  const ambiguous: string[] = [];
  for (const p of people) {
    if (COMMON_ENGLISH_WORDS.has(p.name.toLowerCase())) {
      ambiguous.push(p.name);
    }
  }
  return ambiguous;
}

/**
 * Generate AAAK entity registry + critical facts bootstrap from onboarding data.
 * Writes ~/.mempalace/aaak_entities.md and critical_facts.md
 */
export function generateAaakBootstrap(
  people: OnboardingPerson[],
  projects: string[],
  wings: string[],
  mode: string,
  configDir?: string,
): { aaakEntitiesPath: string; criticalFactsPath: string } {
  const mempalaceDir = configDir || path.join(os.homedir(), '.mempalace');
  fs.mkdirSync(mempalaceDir, { recursive: true });

  // Build AAAK entity codes
  const entityCodes: Record<string, string> = {};
  const usedCodes = new Set<string>();
  for (const p of people) {
    let code = p.name.slice(0, 3).toUpperCase();
    let i = 4;
    while (usedCodes.has(code)) {
      code = p.name.slice(0, i).toUpperCase();
      i++;
    }
    entityCodes[p.name] = code;
    usedCodes.add(code);
  }

  // AAAK entity registry
  const registryLines = [
    '# AAAK Entity Registry',
    '# Auto-generated by mempalace init. Update as needed.',
    '',
    '## People',
  ];
  for (const p of people) {
    const code = entityCodes[p.name];
    const rel = p.relationship || '';
    registryLines.push(rel ? `  ${code}=${p.name} (${rel})` : `  ${code}=${p.name}`);
  }

  if (projects.length > 0) {
    registryLines.push('', '## Projects');
    for (const proj of projects) {
      const code = proj.slice(0, 4).toUpperCase();
      registryLines.push(`  ${code}=${proj}`);
    }
  }

  registryLines.push(
    '',
    '## AAAK Quick Reference',
    '  Symbols: ♡=love ★=importance ⚠=warning →=relationship |=separator',
    '  Structure: KEY:value | GROUP(details) | entity.attribute',
    '  Read naturally — expand codes, treat *markers* as emotional context.',
  );

  const aaakEntitiesPath = path.join(mempalaceDir, 'aaak_entities.md');
  fs.writeFileSync(aaakEntitiesPath, registryLines.join('\n'));

  // Critical facts bootstrap
  const factsLines = ['# Critical Facts (bootstrap — will be enriched after mining)', ''];

  const personalPeople = people.filter(p => p.context === 'personal');
  const workPeople = people.filter(p => p.context === 'work');

  if (personalPeople.length > 0) {
    factsLines.push('## People (personal)');
    for (const p of personalPeople) {
      const code = entityCodes[p.name];
      const rel = p.relationship || '';
      factsLines.push(rel ? `- **${p.name}** (${code}) — ${rel}` : `- **${p.name}** (${code})`);
    }
    factsLines.push('');
  }

  if (workPeople.length > 0) {
    factsLines.push('## People (work)');
    for (const p of workPeople) {
      const code = entityCodes[p.name];
      const rel = p.relationship || '';
      factsLines.push(rel ? `- **${p.name}** (${code}) — ${rel}` : `- **${p.name}** (${code})`);
    }
    factsLines.push('');
  }

  if (projects.length > 0) {
    factsLines.push('## Projects');
    for (const proj of projects) {
      factsLines.push(`- **${proj}**`);
    }
    factsLines.push('');
  }

  factsLines.push(
    '## Palace',
    `Wings: ${wings.join(', ')}`,
    `Mode: ${mode}`,
    '',
    '*This file will be enriched by palace_facts after mining.*',
  );

  const criticalFactsPath = path.join(mempalaceDir, 'critical_facts.md');
  fs.writeFileSync(criticalFactsPath, factsLines.join('\n'));

  return { aaakEntitiesPath, criticalFactsPath };
}

/**
 * Run the full onboarding flow programmatically.
 * Returns the seeded EntityRegistry.
 */
export function runOnboarding(config: OnboardingConfig): {
  registry: EntityRegistry;
  ambiguous: string[];
  bootstrap: { aaakEntitiesPath: string; criticalFactsPath: string };
} {
  const wings = config.wings || DEFAULT_WINGS[config.mode];
  const projects = config.projects || [];

  const registry = EntityRegistry.load(config.configDir);
  registry.seed(config.mode, config.people, projects, config.aliases || {});

  const bootstrap = generateAaakBootstrap(config.people, projects, wings, config.mode, config.configDir);
  const ambiguous = warnAmbiguous(config.people);

  return { registry, ambiguous, bootstrap };
}

/**
 * Quick setup — non-interactive, for tests and benchmarks.
 */
export function quickSetup(
  mode: OnboardingMode,
  people: OnboardingPerson[],
  projects: string[] = [],
  aliases: Record<string, string> = {},
  configDir?: string,
): EntityRegistry {
  const registry = EntityRegistry.load(configDir);
  registry.seed(mode, people, projects, aliases);
  return registry;
}
